### ISSUE TITLE
How to structure CI/CD pipeline with this approach?

### ISSUE THREAD

**Issue by nextah** [manfredsteyer/module-federation-plugin-example#7]
Hey @manfredsteyer,

first of all - thank you for this module federation repository!
I was wondering how you would handle this setup in a pipeline? How can you still build individual microfrontends when working in one repository?
Do you use tags to trigger the pipeline?

Love to hear your thoughts on that!
Kind regards,
Thomas

**Comment by JP-Jagadesan** [comment]
Hi Ghost,
 i can see the issue is closed. It would be helpful if you share the docs or links on how you solved the above mentioned problem.

Regards,
Jagadesan
